stages:
  - test
  - deploy

services:
  - docker:dind

test:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install -r requirements.txt
    - python -m pytest

production:
  stage: deploy
  image: docker:latest

  before_script:
    - docker info
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD

  script:
    - docker build -t inowas/processing:latest .
    - docker push inowas/processing

  only:
    - master
